name: AI Integrated Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Run Python script
        run: |
          echo "print('Hello, World!')" > hello.py
          python hello.py

      - name: OpenAI Code Generator
        uses: https://github.com/JuliusHaring/llm-code-gen@main
        with:
          descriptions: 'Generate Dockerfiles for this project'
          openai_token: ${{ secrets.OPENAI_TOKEN }}